# key snippets to search for when debug log level set:
    #1. Identified candidate component class
    #2. Searching directory
    #3. Autowiring by type from bean
logging.level:
 root: warn
 org:
  springframework.*: info
  springframework.boot.devtools: trace
 com.ker.springboot: trace
 org.hibernate.SQL: debug
 org.hibernate.type: trace

dev.test.url: http://dev-test.com